-- Create materials table
CREATE TABLE IF NOT EXISTS public.materials (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    title TEXT NOT NULL,
    description TEXT,
    image_url TEXT,
    external_url TEXT,
    price TEXT,
    category TEXT,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
    created_by UUID REFERENCES auth.users(id)
);

-- Enable RLS
ALTER TABLE public.materials ENABLE ROW LEVEL SECURITY;

-- Policies
CREATE POLICY "Allow public read access on materials" 
ON public.materials FOR SELECT 
USING (true);

CREATE POLICY "Allow admin to manage materials" 
ON public.materials FOR ALL 
USING (
  EXISTS (
    SELECT 1 FROM public.profiles
    WHERE profiles.id = auth.uid() 
    AND profiles.role = 'admin'
  )
);
